# Generated by Django 4.1.3 on 2022-12-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('typeOfPublication', models.CharField(max_length=50)),
                ('publisther', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=50)),
                ('yearOfPublication', models.IntegerField()),
                ('doi', models.CharField(max_length=300)),
            ],
        ),
    ]
