# Generated by Django 4.1.3 on 2022-12-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_journal_authorname_alter_journal_doi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='authorName',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='isbn',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publisther',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='typeOfPublication',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
