# Generated by Django 4.1.3 on 2022-12-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_journal_authorname_alter_journal_isbn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='publisther',
            new_name='publisher',
        ),
    ]
