# Generated by Django 4.1.3 on 2022-12-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_conference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='journal',
        ),
    ]
