# Generated by Django 4.1.3 on 2022-12-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_delete_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('titleOfManuscript', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('typeOfJournal', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('titleOfJournal', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('publisher', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('issn', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('yearOfPublication', models.IntegerField(blank=True, default=None, null=True)),
                ('doi', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
        ),
    ]
